spring:
  application:
    name: nl2sql-schema-service
  config:
    import:
      - nacos:nl2sql-common.yml?group=DEFAULT_GROUP
      - nacos:nl2sql-schema-service.yml?group=DEFAULT_GROUP
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
